### ISSUE TITLE
Klasa Node

### ISSUE THREAD

**Issue by WinCubeML** [SiwyKrzysiek/tdd#2]
- id
- lista sąsiadów
- miejsce na wagę (wagi zapisujemy jako wartość danej krawędzi. Tu to jest tylko przechowalnia. Potrzebne dla Dijkstry i Bellmana-Forda)

**Comment by christopher-dabrowski** [comment]
Wiem, że Olszewski byłyby pod wrażeniem, gdybyśmy użyli `Optional<>` do trzymania wag
